### ISSUE TITLE
Sokobot doesn't accept the token

### ISSUE THREAD

**Issue by tabbeddev** [PolyMarsDev/Sokobot#61]
Hello, I want to run Sokobot on my Raspberry Pi.

But then I got this funny error:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Loaded 15 commands
[JDA RateLimit-Worker 1] ERROR RateLimiter - Encountered exception trying to execute request
java.lang.IllegalArgumentException: Unexpected char 0x0a at 74 in authorization value: Bot OTg2OTc0NDM5MTc2NTY0Nzc3.GpnoIr.95CBQahGMe-GAv8KlgFY52Y73SC_c4VEMLtYec

	at okhttp3.Headers.checkValue(Headers.java:284)
	at okhttp3.Headers$Builder.set(Headers.java:415)
	at okhttp3.Request$Builder.header(Request.java:184)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:172)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:139)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:122)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I have a valid token.txt in the same directory.
And I open it with : `java -jar Sokobot.jar`

**Comment by minihoot** [comment]
try reset it, then put the new token in

**Comment by tabbeddev** [comment]
It still doesn't work.

**Comment by minihoot** [comment]
maybe try another device, i'm not sure
